### ISSUE TITLE
Deprecation warnings in PHPUnit tests on PHP 8

### ISSUE THREAD

**Issue by dregad** [dokuwiki/dokuwiki#3948]
Reviewing PHPUnit tests logs following my recent PR, I noticed a number of deprecation warnings on PHP 8.1 and 8.2 runs

- [x] Creation of dynamic property IXR\Message\Message::$currentTag  is deprecated in /home/runner/work/dokuwiki/dokuwiki/vendor/kissifrot/php-ixr/src/Message/Message.php on line 105 <br> => Reported upstream https://github.com/kissifrot/php-ixr/issues/7
- [ ] preg_match(): Passing null to parameter \# 4 ($flags) of type int is deprecated in /home/runner/work/dokuwiki/dokuwiki/vendor/marcusschwarz/lesserphp/lessc.inc.php on line 3739 <br> => Reported upstream: https://github.com/MarcusSchwarz/lesserphp/issues/23
- [x] Passing null to parameter # 3 ($subject) of type array|string is deprecated in /home/runner/work/dokuwiki/dokuwiki/inc/ChangeLog/ChangeLogTrait.php on line 62 <br> Proposed fix in PR #3947
- [x]  Creation of dynamic property _HWLDF_WordAccumulator::$_lines / $_line / $_group / $_tag is deprecated in /home/runner/work/dokuwiki/dokuwiki/inc/DifferenceEngine.php on line 933 <br> Proposed fix in PR #3947

There's a few more that I have not logged yet, but I have to run... will finish later.

There is also a lot of strftime() occurrences, but I guess that is already covered by #3573.

**Comment by dregad** [comment]
https://github.com/kissifrot/php-ixr/issues/7 has been fixed and new [XML-RPC version 1.8.4 has been released](https://github.com/kissifrot/php-ixr/releases/tag/1.8.4 released).

**Comment by dregad** [comment]
lesserphp still throws a bunch of deprecation warnings (PHP 8.2)

```
Creation of dynamic property lessc::$env is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2084
Creation of dynamic property lessc::$formatter is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2088
Creation of dynamic property lessc::$parser is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2081
Creation of dynamic property lessc::$scope is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2085
Creation of dynamic property lessc_formatter_lessjs::$indentLevel is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 3924
Creation of dynamic property lessc_parser::$buffer is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2581
Creation of dynamic property lessc_parser::$count is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2577
Creation of dynamic property lessc_parser::$eatWhiteDefault is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2554
Creation of dynamic property lessc_parser::$env is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2580
Creation of dynamic property lessc_parser::$inExp is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2865
Creation of dynamic property lessc_parser::$lessc is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2556
Creation of dynamic property lessc_parser::$line is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2578
Creation of dynamic property lessc_parser::$seenComments is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2584
Creation of dynamic property lessc_parser::$sourceName is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2558
Creation of dynamic property lessc_parser::$writeComments is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 2560
Passing null to parameter #4 ($flags) of type int is deprecated in ./marcusschwarz/lesserphp/lessc.inc.php on line 3739
Using ${var} in strings is deprecated, use {$var} instead in ./marcusschwarz/lesserphp/lessc.inc.php on line 1379
Using ${var} in strings is deprecated, use {$var} instead in ./marcusschwarz/lesserphp/lessc.inc.php on line 1395
Using ${var} in strings is deprecated, use {$var} instead in ./marcusschwarz/lesserphp/lessc.inc.php on line 1740
```

**Comment by dregad** [comment]
Since #4088 has been resolved by e6380ba37d6b3f7dd03146b3c03030ccc8c1b297, I believe this one can be closed as well, as the lesserphp issues were the only point left open.
